// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/todo/v1/todo.proto

package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// @inject_tag: sql:",notnull,default:false"
	Completed bool `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: sql:"type:timestamptz"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Foo                  string               `protobuf:"bytes,7,opt,name=foo,proto3" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_69530c67f21d0664, []int{0}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Todo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Todo) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Todo) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

type CreateTodoRequest struct {
	Item                 *Todo    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_69530c67f21d0664, []int{1}
}
func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(dst, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetItem() *Todo {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateTodoResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoResponse) Reset()         { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()    {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_69530c67f21d0664, []int{2}
}
func (m *CreateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoResponse.Unmarshal(m, b)
}
func (m *CreateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoResponse.Merge(dst, src)
}
func (m *CreateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTodoResponse.Size(m)
}
func (m *CreateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoResponse proto.InternalMessageInfo

func (m *CreateTodoResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "todo.v1.Todo")
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.v1.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.v1.CreateTodoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := c.cc.Invoke(ctx, "/todo.v1.TodoService/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.v1.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/todo/v1/todo.proto",
}

func init() { proto.RegisterFile("api/todo/v1/todo.proto", fileDescriptor_todo_69530c67f21d0664) }

var fileDescriptor_todo_69530c67f21d0664 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xa5, 0x4d, 0xdb, 0x5f, 0x27, 0x28, 0xba, 0x88, 0x2c, 0x51, 0x30, 0x06, 0x0f, 0x39,
	0x6d, 0x68, 0x05, 0xc1, 0x63, 0xf5, 0xe0, 0x3d, 0x16, 0x0f, 0x5e, 0x24, 0xcd, 0x4e, 0xcb, 0x42,
	0xd3, 0x59, 0x93, 0x69, 0x3f, 0xb9, 0x1f, 0x40, 0xb2, 0x69, 0x6d, 0x51, 0xc1, 0x53, 0x26, 0xef,
	0xcf, 0xec, 0x9b, 0x07, 0xe7, 0xb9, 0x35, 0x29, 0x93, 0xa6, 0x74, 0x33, 0x72, 0x5f, 0x65, 0x2b,
	0x62, 0x12, 0x03, 0x37, 0x6f, 0x46, 0xe1, 0xd5, 0x82, 0x68, 0xb1, 0xc4, 0xd4, 0xc1, 0xb3, 0xf5,
	0x3c, 0x65, 0x53, 0x62, 0xcd, 0x79, 0x69, 0x5b, 0x65, 0xfc, 0xe1, 0x81, 0x3f, 0x25, 0x4d, 0xe2,
	0x18, 0x3a, 0x46, 0x4b, 0x2f, 0xf2, 0x12, 0x3f, 0xeb, 0x18, 0x2d, 0xce, 0xa0, 0xc7, 0x86, 0x97,
	0x28, 0x3b, 0x91, 0x97, 0x0c, 0xb3, 0xf6, 0x47, 0x44, 0x10, 0x68, 0xac, 0x8b, 0xca, 0x58, 0x36,
	0xb4, 0x92, 0x5d, 0xc7, 0x1d, 0x42, 0xe2, 0x12, 0x86, 0x05, 0x95, 0x76, 0x89, 0x8c, 0x5a, 0xfa,
	0x91, 0x97, 0xfc, 0xcf, 0xf6, 0x80, 0xb8, 0x07, 0x28, 0x2a, 0xcc, 0x19, 0xf5, 0x5b, 0xce, 0xb2,
	0x17, 0x79, 0x49, 0x30, 0x0e, 0x55, 0x1b, 0x52, 0xed, 0x42, 0xaa, 0xe9, 0x2e, 0x64, 0x36, 0xdc,
	0xaa, 0x27, 0xdc, 0x58, 0xd7, 0x56, 0xef, 0xac, 0xfd, 0xbf, 0xad, 0x5b, 0xf5, 0x84, 0xc5, 0x09,
	0x74, 0xe7, 0x44, 0x72, 0xe0, 0xd2, 0x36, 0x63, 0x7c, 0x07, 0xa7, 0x8f, 0x6e, 0x73, 0x73, 0x7b,
	0x86, 0xef, 0x6b, 0xac, 0x59, 0x5c, 0x83, 0x6f, 0x18, 0x4b, 0x57, 0x42, 0x30, 0x3e, 0x52, 0xdb,
	0x12, 0x95, 0xd3, 0x38, 0x2a, 0xbe, 0x01, 0x71, 0xe8, 0xab, 0x2d, 0xad, 0x6a, 0xfc, 0xde, 0xdd,
	0xf8, 0x05, 0x82, 0x86, 0x7f, 0xc6, 0x6a, 0x63, 0x0a, 0x14, 0x4f, 0x00, 0x7b, 0x93, 0x08, 0xbf,
	0xf6, 0xfe, 0x48, 0x10, 0x5e, 0xfc, 0xca, 0xb5, 0xaf, 0xc4, 0xff, 0x1e, 0xfa, 0xaf, 0x7e, 0xc3,
	0xcf, 0xfa, 0xee, 0xdc, 0xdb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xa9, 0xc4, 0x7f, 0xff,
	0x01, 0x00, 0x00,
}
